"""Bootstrap docs/te_sources_truth.yaml from the live indicator_sources table.

Extracts every (country, indicator) where is_default=true AND active=true and
writes a YAML skeleton with the *current* source. Each entry starts as
`verified: false` — the next step (sub-agent TE inventory) verifies te_label/
te_url against tradingeconomics.com and flips `verified: true` (and corrects
`source` if it diverges from the TE-attributed provider).

The YAML is the single source of truth for `pipeline/validate_te_conformity.py`.

Usage: pipeline/.venv/Scripts/python.exe -m pipeline.bootstrap_truth_yaml
"""
from __future__ import annotations

import os
from collections import defaultdict

from pipeline.db import supabase

OUTPUT = os.path.join(os.path.dirname(__file__), "..", "docs", "te_sources_truth.yaml")


def _yaml_escape(value: str) -> str:
    """Minimal YAML-safe quote: escape backslashes + double-quotes, wrap in quotes."""
    s = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{s}"'


def fetch_default_rows() -> list[dict]:
    """Paginated fetch — Supabase caps at 1000 rows per request."""
    rows: list[dict] = []
    page = 0
    while True:
        start = page * 1000
        end = start + 999
        r = (
            supabase.table("indicator_sources")
            .select("country, indicator, source, note")
            .eq("is_default", True)
            .eq("active", True)
            .range(start, end)
            .execute()
        )
        chunk = r.data or []
        rows.extend(chunk)
        if len(chunk) < 1000:
            break
        page += 1
    return rows


def group_by_country(rows: list[dict]) -> dict[str, dict[str, dict]]:
    grouped: dict[str, dict[str, dict]] = defaultdict(dict)
    for row in rows:
        c = row["country"]
        i = row["indicator"]
        grouped[c][i] = {"source": row["source"], "note": row.get("note") or ""}
    return grouped


def write_yaml(grouped: dict[str, dict[str, dict]], path: str) -> int:
    lines: list[str] = []
    lines.append("# TE-Source-Truth — single source of truth for (country, indicator) -> source.")
    lines.append("# Generated by pipeline.bootstrap_truth_yaml from indicator_sources (is_default=true, active=true).")
    lines.append("# Sub-agent inventory then verifies te_label / te_url against tradingeconomics.com")
    lines.append("# and flips verified: true. Edits to this file are intentional overrides.")
    lines.append("#")
    lines.append("# Schema per entry:")
    lines.append("#   source:    internal source code (must exist in src/lib/sources.ts STATIC_LABELS)")
    lines.append("#   te_label:  exact provider name as shown on tradingeconomics.com (filled by inventory)")
    lines.append("#   te_url:    provider website URL (filled by inventory)")
    lines.append("#   te_page:   TE indicator page (filled by inventory)")
    lines.append("#   stage:     1 = Tier-1 mandatory, 2 = Stage-2 expansion, gap = licensed/unavailable")
    lines.append("#   verified:  true once the sub-agent confirmed source matches TE's attribution")
    lines.append("")

    total = 0
    for country in sorted(grouped.keys()):
        lines.append(f"{country}:")
        for indicator in sorted(grouped[country].keys()):
            entry = grouped[country][indicator]
            src = entry["source"]
            note = entry["note"]
            parts = [f"source: {src}", "verified: false"]
            if note:
                parts.append(f"note: {_yaml_escape(note)}")
            lines.append(f"  {indicator}: {{ {', '.join(parts)} }}")
            total += 1
        lines.append("")

    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    return total


def main():
    print("Fetching indicator_sources (is_default=true, active=true)...")
    rows = fetch_default_rows()
    print(f"  {len(rows)} rows fetched")
    grouped = group_by_country(rows)
    print(f"  {len(grouped)} countries, {sum(len(v) for v in grouped.values())} (country, slug) pairs")
    n = write_yaml(grouped, OUTPUT)
    print(f"Wrote {n} entries to {OUTPUT}")


if __name__ == "__main__":
    main()
