"""Merge per-country TE inventory snapshots into docs/te_sources_truth.yaml.

Inputs:
  docs/_te_inventory/<CC>.yaml — sub-agent outputs with shape
    { <slug>: { te_label, te_url, te_page, te_value, te_period,
                suggested_source, current_source, conform, verified } }

Output:
  docs/te_sources_truth.yaml — same structure as bootstrap but with
    source set to the TE-suggested code when verified, plus te_label/te_url
    /te_page enriched and verified=true. Entries where the inventory could
    not verify keep their bootstrap state (source = DB current, verified=false).

Rules:
  - If inventory verified=true AND suggested_source is non-null:
      truth.source = suggested_source
      truth.te_label/te_url/te_page = from inventory
      truth.verified = true
  - If inventory verified=true AND suggested_source is null:
      truth keeps DB source, adds te_label (for licensed/gap), verified=true
  - If inventory verified=false: pass through unchanged
  - Entries missing from inventory: pass through unchanged

Run: pipeline/.venv/Scripts/python.exe -m pipeline.merge_te_inventory
"""
from __future__ import annotations

import os
from pathlib import Path

import yaml

DOCS = Path(__file__).parent.parent / "docs"
TRUTH = DOCS / "te_sources_truth.yaml"
INV_DIR = DOCS / "_te_inventory"


def _yaml_escape(s: str) -> str:
    s = (s or "").replace("\\", "\\\\").replace('"', '\\"')
    return f'"{s}"'


def main():
    if not INV_DIR.exists():
        raise SystemExit(f"Inventory dir not found: {INV_DIR}")

    # 1) Load current truth.yaml
    with open(TRUTH, encoding="utf-8") as f:
        truth = yaml.safe_load(f) or {}

    # 2) Load inventory snapshots per country
    inventory: dict[str, dict] = {}
    for fp in sorted(INV_DIR.glob("*.yaml")):
        cc = fp.stem
        with open(fp, encoding="utf-8") as f:
            inventory[cc] = yaml.safe_load(f) or {}

    print(f"Inventory loaded: {len(inventory)} countries — {sum(len(v) for v in inventory.values())} (country, slug) pairs")

    # 3) Merge per (country, slug)
    n_promoted = 0
    n_verified_kept = 0
    n_licensed = 0
    n_pass = 0
    for cc, slugs in inventory.items():
        if cc not in truth:
            truth[cc] = {}
        for slug, inv in slugs.items():
            existing = truth.get(cc, {}).get(slug, {})
            if not isinstance(inv, dict):
                continue
            verified = inv.get("verified", False)
            te_label = inv.get("te_label")
            te_url = inv.get("te_url")
            te_page = inv.get("te_page")
            suggested = inv.get("suggested_source")

            if not verified:
                n_pass += 1
                # Still record te_page if available for follow-up
                if te_page and slug in truth.get(cc, {}):
                    truth[cc][slug]["te_page"] = te_page
                continue

            if suggested:
                # Verified and suggests a TE-conform source.
                old_source = existing.get("source")
                truth[cc][slug] = {
                    "source": suggested,
                    "te_label": te_label or "",
                    "te_url": te_url or "",
                    "te_page": te_page or "",
                    "verified": True,
                }
                if old_source != suggested:
                    n_promoted += 1
                else:
                    n_verified_kept += 1
            else:
                # Verified but no internal code (licensed / unmapped).
                truth[cc][slug] = {
                    "source": existing.get("source", "curated"),
                    "te_label": te_label or "",
                    "te_url": te_url or "",
                    "te_page": te_page or "",
                    "verified": True,
                    "note": "no internal source code — likely licensed or unmapped provider",
                }
                n_licensed += 1

    print(f"  promoted (source changed): {n_promoted}")
    print(f"  verified (source matched): {n_verified_kept}")
    print(f"  licensed/unmapped:         {n_licensed}")
    print(f"  unverified pass-through:   {n_pass}")

    # 4) Write back truth.yaml
    lines: list[str] = []
    lines.append("# TE-Source-Truth — single source of truth for (country, indicator) -> source.")
    lines.append("# Generated by pipeline.bootstrap_truth_yaml, enriched by pipeline.merge_te_inventory.")
    lines.append("# Entries with verified: true were checked against the TE indicator page; source = TE-attributed provider.")
    lines.append("# Entries with verified: false reflect DB state and need a follow-up inventory pass.")
    lines.append("#")
    lines.append("# Schema:")
    lines.append("#   source:    internal source code (must exist in src/lib/sources.ts STATIC_LABELS)")
    lines.append("#   te_label:  exact provider name as shown on tradingeconomics.com")
    lines.append("#   te_url:    provider website URL")
    lines.append("#   te_page:   TE indicator page (for audit/spot-check)")
    lines.append("#   verified:  true after sub-agent inventory confirmed source matches TE")
    lines.append("#   note:      optional, e.g. licensed/gap explanation")
    lines.append("")

    total = 0
    for cc in sorted(truth.keys()):
        lines.append(f"{cc}:")
        for slug in sorted(truth[cc].keys()):
            entry = truth[cc][slug] or {}
            src = entry.get("source", "eurostat")
            verified = entry.get("verified", False)
            parts = [f"source: {src}", f"verified: {str(verified).lower()}"]
            if entry.get("te_label"):
                parts.append(f"te_label: {_yaml_escape(entry['te_label'])}")
            if entry.get("te_url"):
                parts.append(f"te_url: {_yaml_escape(entry['te_url'])}")
            if entry.get("te_page"):
                parts.append(f"te_page: {_yaml_escape(entry['te_page'])}")
            if entry.get("note"):
                parts.append(f"note: {_yaml_escape(entry['note'])}")
            lines.append(f"  {slug}: {{ {', '.join(parts)} }}")
            total += 1
        lines.append("")

    with open(TRUTH, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    print(f"Wrote {total} entries to {TRUTH}")


if __name__ == "__main__":
    main()
