"""Update docs/te_sources_truth.yaml BG section based on fresh re-audit."""
import json, yaml, re
from datetime import date

TODAY = date.today().isoformat()

# Mapping of slug -> updated truth entry. Source label = TECHNICAL fetch source (honest).
# te_label = what TE attributes upstream.

UPDATES = {
    # Already verified - just refresh reaudited date
    "budget-deficit": {
        "source": "nsi_bg",
        "te_label": "Ministry of Finance of the Republic of Bulgaria",
        "te_page": "https://tradingeconomics.com/bulgaria/government-budget-value",
        "te_url": "https://www.minfin.bg",
        "note": "BNB CGO GBXCCB cash basis monthly mln BGN. TE says -1036.81 BGN Million Mar 2026; DB matches via NSI/BNB SDDS.",
        "verified": True,
    },
    "business-confidence": {
        "source": "eurostat",
        "te_label": "National Statistical Institute, Bulgaria",
        "te_page": "https://tradingeconomics.com/bulgaria/business-confidence",
        "te_url": "https://www.nsi.bg",
        "note": "Eurostat ei_bsin_m_r2 BCI for BG (NSI publishes the BCS upstream; honest fetch label kept eurostat).",
        "verified": True,
    },
    "capacity-utilization": {
        "source": "eurostat",
        "te_label": "European Commission",
        "te_page": "https://tradingeconomics.com/bulgaria/capacity-utilization",
        "te_url": "https://ec.europa.eu",
        "note": "Eurostat ei_bsin_q_r2 BS-ICU-PC. TE 73.5 Q1 2026; DB 74.5 Q2 2026.",
        "verified": True,
    },
    "changes-in-inventories": {
        "source": "nsi_bg",
        "te_label": "National Statistical Institute, Bulgaria",
        "te_page": "https://tradingeconomics.com/bulgaria/changes-in-inventories",
        "te_url": "https://www.nsi.bg",
        "note": "NSI BG NAG P5M current prices mln BGN. TE 357.62 Q4 2025; DB 194.92 (units check pending).",
        "verified": True,
    },
    "consumer-confidence": {
        "source": "eurostat",
        "te_label": "National Statistical Institute, Bulgaria",
        "te_page": "https://tradingeconomics.com/bulgaria/consumer-confidence",
        "te_url": "https://www.nsi.bg",
        "note": "Eurostat ei_bsco_m BS-CSMCI for BG; TE -28.6 Q2 2026; DB -20.6 Apr 2026. Quarterly avg vs monthly.",
        "verified": True,
    },
    "consumer-spending": {
        "source": "nsi_bg",
        "te_label": "National Statistical Institute, Bulgaria",
        "te_page": "https://tradingeconomics.com/bulgaria/consumer-spending",
        "te_url": "https://www.nsi.bg",
        "note": "NSI BG NAG P31 household final consumption mln BGN. TE 31365 Q4 2025; DB 20047 (concept: P31 S1M vs aggregate).",
        "verified": True,
    },
    "core-cpi": {
        "source": "eurostat",
        "te_label": "EUROSTAT",
        "te_page": "https://tradingeconomics.com/bulgaria/core-inflation-rate",
        "te_url": "https://ec.europa.eu/eurostat/",
        "note": "Eurostat ei_cphi_m CP-HI00XEF (HICP excl. energy & unprocessed food). TE 4.60% YoY Apr 2026; DB 102.96 index level. Frontend computes YoY.",
        "verified": True,
    },
    "corporate-tax-rate": {
        "source": "curated",
        "te_label": "National Revenue Agency, Bulgaria",
        "te_page": "https://tradingeconomics.com/bulgaria/corporate-tax-rate",
        "te_url": "https://www.nra.bg",
        "note": "BG flat rate 10%. Curated row.",
        "verified": True,
    },
    "corruption-index": {
        "source": "curated",
        "te_label": "Transparency International",
        "te_page": "https://tradingeconomics.com/bulgaria/corruption-index",
        "te_url": "https://www.transparency.org",
        "note": "TI CPI 2025 score 40/100; DB has 43 (2024). Refresh curated to 2025.",
        "verified": True,
    },
    "corruption-rank": {
        "source": "curated",
        "te_label": "Transparency International",
        "te_page": "https://tradingeconomics.com/bulgaria/corruption-rank",
        "te_url": "https://www.transparency.org",
        "note": "TI CPI 2025 rank. DB has 76 (2024).",
        "verified": True,
    },
    "cpi-clothing": {
        "source": "eurostat",
        "te_label": "National Statistical Institute, Bulgaria",
        "te_page": "https://tradingeconomics.com/bulgaria/cpi-clothing",
        "te_url": "https://www.nsi.bg",
        "note": "Eurostat ei_cphi_m CP-HI03 (HICP 2025=100). TE 102.59 Apr; DB 95.52 Mar (need refresh).",
        "verified": True,
    },
    "cpi-education": {
        "source": "eurostat",
        "te_label": "National Statistical Institute, Bulgaria",
        "te_page": "https://tradingeconomics.com/bulgaria/cpi-education",
        "te_url": "https://www.nsi.bg",
        "note": "Eurostat ei_cphi_m CP-HI10 (HICP 2025=100). DB has Mar 2026.",
        "verified": True,
    },
    "cpi-food": {
        "source": "eurostat",
        "te_label": "National Statistical Institute, Bulgaria",
        "te_page": "https://tradingeconomics.com/bulgaria/cpi-food",
        "te_url": "https://www.nsi.bg",
        "note": "Eurostat ei_cphi_m CP-HI01. TE 105.26 Apr; DB 103.03 Mar (refresh).",
        "verified": True,
    },
    "cpi-housing-utilities": {
        "source": "eurostat",
        "te_label": "National Statistical Institute, Bulgaria",
        "te_page": "https://tradingeconomics.com/bulgaria/cpi-housing-utilities",
        "te_url": "https://www.nsi.bg",
        "note": "Eurostat ei_cphi_m CP-HI04. DB has Mar 2026.",
        "verified": True,
    },
    "cpi-recreation-and-culture": {
        "source": "eurostat",
        "te_label": "National Statistical Institute, Bulgaria",
        "te_page": "https://tradingeconomics.com/bulgaria/cpi-recreation-and-culture",
        "te_url": "https://www.nsi.bg",
        "note": "Eurostat ei_cphi_m CP-HI09. DB has Mar 2026.",
        "verified": True,
    },
    "cpi-transportation": {
        "source": "eurostat",
        "te_label": "National Statistical Institute, Bulgaria",
        "te_page": "https://tradingeconomics.com/bulgaria/cpi-transportation",
        "te_url": "https://www.nsi.bg",
        "note": "Eurostat ei_cphi_m CP-HI07. TE 119.5 Apr; DB 104.16 Mar (refresh).",
        "verified": True,
    },
    "credit-rating": {
        "source": "curated",
        "te_label": "TE Credit Rating Composite",
        "te_page": "https://tradingeconomics.com/bulgaria/rating",
        "te_url": "https://tradingeconomics.com/country-list/rating",
        "note": "Curated composite of S&P/Moody's/Fitch.",
        "verified": True,
    },
    "current-account": {
        "source": "nsi_bg",
        "te_label": "Bulgarian National Bank",
        "te_page": "https://tradingeconomics.com/bulgaria/current-account",
        "te_url": "https://www.bnb.bg",
        "note": "BNB SDDS Plus BOP BPM6 CA/B mln EUR. TE -170 EUR M Feb 2026 = DB -170.1 ✓.",
        "verified": True,
    },
    "current-account-to-gdp": {
        "source": "eurostat",
        "te_label": "Bulgarian National Bank",
        "te_page": "https://tradingeconomics.com/bulgaria/current-account-to-gdp",
        "te_url": "https://www.bnb.bg",
        "note": "Eurostat bop_gdp6_q quarterly CA % GDP (honest fetch source).",
        "verified": True,
    },
    "disposable-personal-income": {
        "source": "eurostat",
        "te_page": "https://tradingeconomics.com/bulgaria/disposable-personal-income",
        "note": "TE has NO BG page for this slug. Coverage-gap; kept as EconPulse-internal via Eurostat nasq_10_nf_tr B6G.",
        "verified": True,
    },
    "employed-persons": {
        "source": "nsi_bg",
        "te_label": "National Statistical Institute, Bulgaria",
        "te_page": "https://tradingeconomics.com/bulgaria/employed-persons",
        "te_url": "https://www.nsi.bg",
        "note": "NSI BG LE_PE_NUM Thousand quarterly. TE 2919.5 Q4 2025; DB 2794.8 (concept diff: LFS vs NA).",
        "verified": True,
    },
    "employment-rate": {
        "source": "eurostat",
        "te_label": "National Statistical Institute, Bulgaria",
        "te_page": "https://tradingeconomics.com/bulgaria/employment-rate",
        "te_url": "https://www.nsi.bg",
        "note": "Eurostat lfsa_ergan Y15-64. TE 53.1 Q4 (15+); DB 70.9 Y15-64. Concept mismatch.",
        "verified": True,
    },
    "energy-inflation": {
        "source": "eurostat",
        "te_page": "https://tradingeconomics.com/bulgaria/energy-inflation",
        "note": "TE has NO BG page. Internal slug via Eurostat ei_cphi_m CP-HIE.",
        "verified": True,
    },
    "exports": {
        "source": "nsi_bg",
        "te_label": "National Statistical Institute, Bulgaria",
        "te_page": "https://tradingeconomics.com/bulgaria/exports",
        "te_url": "https://www.nsi.bg",
        "note": "NSI BG NAG P6 current prices mln BGN. TE 4095 EUR M Mar 2026 (monthly trade); DB quarterly mln BGN. Different concept (monthly trade vs NA quarterly).",
        "verified": True,
    },
    "food-inflation": {
        "source": "eurostat",
        "te_label": "National Statistical Institute, Bulgaria",
        "te_page": "https://tradingeconomics.com/bulgaria/food-inflation",
        "te_url": "https://www.nsi.bg",
        "note": "Eurostat ei_cphi_m CP-HIF. TE 5.7% YoY Apr 2026; DB 104.91 index.",
        "verified": True,
    },
    "gdp": {
        "source": "worldbank",
        "te_label": "World Bank",
        "te_page": "https://tradingeconomics.com/bulgaria/gdp",
        "te_url": "https://www.worldbank.org/",
        "note": "WB NY.GDP.MKTP.CD billion USD. TE 112.21 Bn 2024; DB 113.34 (~1% diff, WB revision).",
        "verified": True,
    },
    "gdp-per-capita": {
        "source": "worldbank",
        "te_label": "World Bank",
        "te_page": "https://tradingeconomics.com/bulgaria/gdp-per-capita",
        "te_url": "https://www.worldbank.org/",
        "verified": True,
    },
    "gdp-per-capita-ppp": {
        "source": "worldbank",
        "te_label": "World Bank",
        "te_page": "https://tradingeconomics.com/bulgaria/gdp-per-capita-ppp",
        "te_url": "https://www.worldbank.org/",
        "note": "WB NY.GDP.PCAP.PP.KD. TE 34083 USD 2024; DB 34221 (~0.4%).",
        "verified": True,
    },
    "gdp-real": {
        "source": "nsi_bg",
        "te_label": "National Statistical Institute, Bulgaria",
        "te_page": "https://tradingeconomics.com/bulgaria/gdp-growth-annual",
        "te_url": "https://www.nsi.bg",
        "note": "NSI BG NAG B1GQ chain-linked mln BGN. TE 2.9% YoY Q1 2026; DB 13.71 (NSI chain-linked level; check magnitude).",
        "verified": True,
    },
    "government-debt": {
        "source": "eurostat",
        "te_label": "Ministry of Finance of the Republic of Bulgaria",
        "te_page": "https://tradingeconomics.com/bulgaria/government-debt",
        "te_url": "https://www.minfin.bg",
        "note": "Eurostat gov_10dd_edpt1 GD % GDP. TE shows cash 8174 BGN M from MoF; DB 29.9 % GDP. Concept mismatch.",
        "verified": True,
    },
    "government-debt-total": {
        "source": "eurostat",
        "te_label": "Ministry of Finance of the Republic of Bulgaria",
        "te_page": "https://tradingeconomics.com/bulgaria/government-debt",
        "te_url": "https://www.minfin.bg",
        "note": "Eurostat gov_10dd_edpt1 GD MIO_EUR. DB 34.63 ; concept differs from MoF cash.",
        "verified": True,
    },
    "government-spending": {
        "source": "nsi_bg",
        "te_label": "National Statistical Institute, Bulgaria",
        "te_page": "https://tradingeconomics.com/bulgaria/government-spending",
        "te_url": "https://www.nsi.bg",
        "note": "NSI BG NAG P3 S13 final consumption current prices mln BGN. TE 4452 Q4 2025; DB 7335 (concept diff).",
        "verified": True,
    },
    "government-spending-eur": {
        "source": "eurostat",
        "te_label": "National Statistical Institute, Bulgaria",
        "te_page": "https://tradingeconomics.com/bulgaria/government-spending",
        "te_url": "https://www.nsi.bg",
        "note": "Eurostat namq_10_gdp P3_S13 quarterly. EconPulse-internal EUR-denominated companion to government-spending.",
        "verified": True,
    },
    "gross-fixed-capital-formation": {
        "source": "nsi_bg",
        "te_label": "National Statistical Institute, Bulgaria",
        "te_page": "https://tradingeconomics.com/bulgaria/gross-fixed-capital-formation",
        "te_url": "https://www.nsi.bg",
        "note": "NSI BG NAG P51G current prices mln BGN.",
        "verified": True,
    },
    "hospital-beds": {
        "source": "curated",
        "te_page": "https://tradingeconomics.com/bulgaria/hospital-beds",
        "note": "TE has NO BG page. Curated WHO data.",
        "verified": True,
    },
    "house-price-index": {
        "source": "eurostat",
        "te_label": "EUROSTAT",
        "te_page": "https://tradingeconomics.com/bulgaria/housing-index",
        "te_url": "https://ec.europa.eu/eurostat/",
        "note": "Eurostat prc_hpi_q INX. TE 256.71 Q4 2025 = DB 256.71 ✓ exact match.",
        "verified": True,
    },
    "imports": {
        "source": "nsi_bg",
        "te_label": "National Statistical Institute, Bulgaria",
        "te_page": "https://tradingeconomics.com/bulgaria/imports",
        "te_url": "https://www.nsi.bg",
        "note": "NSI BG NAG P7 current prices mln BGN.",
        "verified": True,
    },
    "industrial-production": {
        "source": "nsi_bg",
        "te_label": "National Statistical Institute, Bulgaria",
        "te_page": "https://tradingeconomics.com/bulgaria/industrial-production",
        "te_url": "https://www.nsi.bg",
        "note": "NSI BG AIP_IX 2021=100. TE 4.8% YoY Mar 2026; DB 94.2 index. Frontend YoY.",
        "verified": True,
    },
    "inflation-cpi": {
        "source": "nsi_bg",
        "te_label": "National Statistical Institute, Bulgaria",
        "te_page": "https://tradingeconomics.com/bulgaria/inflation-cpi",
        "te_url": "https://www.nsi.bg",
        "note": "NSI BG PCPI_IX 2025=100. TE 7.1% YoY Apr 2026; DB 105.39 index level Apr.",
        "verified": True,
    },
    "job-vacancies": {
        "source": "eurostat",
        "te_label": "National Statistical Institute, Bulgaria",
        "te_page": "https://tradingeconomics.com/bulgaria/job-vacancies",
        "te_url": "https://www.nsi.bg",
        "note": "Eurostat jvs_q_nace2 JVR. DB Q4 2025.",
        "verified": True,
    },
    "labor-force-participation-rate": {
        "source": "eurostat",
        "te_label": "National Statistical Institute, Bulgaria",
        "te_page": "https://tradingeconomics.com/bulgaria/labor-force-participation-rate",
        "te_url": "https://www.nsi.bg",
        "note": "Eurostat lfsi_emp_q ACT. TE 54.8 Q4 2025 (15+); DB 73.4 (Y15-64).",
        "verified": True,
    },
    "labour-costs": {
        "source": "eurostat",
        "te_label": "EUROSTAT",
        "te_page": "https://tradingeconomics.com/bulgaria/labour-costs",
        "te_url": "https://ec.europa.eu/eurostat/",
        "note": "Eurostat lc_lci_r2_q I20. TE 186.98 Q4 2025; DB 191.1.",
        "verified": True,
    },
    "long-term-unemployment-rate": {
        "source": "eurostat",
        "te_label": "EUROSTAT",
        "te_page": "https://tradingeconomics.com/bulgaria/long-term-unemployment-rate",
        "te_url": "https://ec.europa.eu/eurostat/",
        "verified": True,
    },
    "manufacturing-production": {
        "source": "eurostat",
        "te_label": "National Statistical Institute, Bulgaria",
        "te_page": "https://tradingeconomics.com/bulgaria/manufacturing-production",
        "te_url": "https://www.nsi.bg",
        "note": "Eurostat sts_inpr_m C I21. TE 4.0% YoY Mar 2026; DB 104.3 index. Frontend YoY.",
        "verified": True,
    },
    "medical-doctors": {
        "source": "curated",
        "te_page": "https://tradingeconomics.com/bulgaria/medical-doctors",
        "note": "TE has NO BG page. Curated WHO.",
        "verified": True,
    },
    "minimum-wages": {
        "source": "curated",
        "te_label": "EUROSTAT",
        "te_page": "https://tradingeconomics.com/bulgaria/minimum-wages",
        "te_url": "https://ec.europa.eu/eurostat/",
        "note": "TE 620 EUR/Month Q2 2026; DB 1077 BGN. Convert 620 EUR * 1.95583 = 1213 BGN. Slight gap; DB shows ~Jan 2026 monthly value, refresh due.",
        "verified": True,
    },
    "mining-production": {
        "source": "eurostat",
        "te_label": "National Statistical Institute of Bulgaria",
        "te_page": "https://tradingeconomics.com/bulgaria/mining-production",
        "te_url": "https://www.nsi.bg",
        "note": "Eurostat sts_inpr_m B I21. TE 27.3% YoY Mar 2026; DB 62.6 index.",
        "verified": True,
    },
    "nurses": {
        "source": "curated",
        "te_page": "https://tradingeconomics.com/bulgaria/nurses",
        "note": "TE has NO BG page. Curated WHO.",
        "verified": True,
    },
    "personal-income-tax-rate": {
        "source": "curated",
        "te_label": "National Revenue Agency, Bulgaria",
        "te_page": "https://tradingeconomics.com/bulgaria/personal-income-tax-rate",
        "te_url": "https://www.nra.bg",
        "note": "BG flat tax 10%. Curated.",
        "verified": True,
    },
    "population": {
        "source": "eurostat",
        "te_label": "National Statistical Institute, Bulgaria",
        "te_page": "https://tradingeconomics.com/bulgaria/population",
        "te_url": "https://www.nsi.bg",
        "note": "Eurostat demo_pjan TOTAL. TE 6.4M 2025; DB 6.44 ✓.",
        "verified": True,
    },
    "ppi": {
        "source": "nsi_bg",
        "te_label": "National Statistical Institute, Bulgaria",
        "te_page": "https://tradingeconomics.com/bulgaria/producer-prices",
        "te_url": "https://www.nsi.bg",
        "note": "NSI BG PPPI_IX 2021=100. TE 149.10 Mar 2026 = DB 149.1 ✓ exact match.",
        "verified": True,
    },
    "productivity": {
        "source": "eurostat",
        "te_label": "EUROSTAT",
        "te_page": "https://tradingeconomics.com/bulgaria/productivity",
        "te_url": "https://ec.europa.eu/eurostat/",
        "note": "Eurostat namq_10_lp_ulc RLPR_HW I20.",
        "verified": True,
    },
    "retail-sales": {
        "source": "eurostat",
        "te_label": "National Statistical Institute, Bulgaria",
        "te_page": "https://tradingeconomics.com/bulgaria/retail-sales",
        "te_url": "https://www.nsi.bg",
        "note": "Eurostat sts_trtu_m G47 I21. TE 2.1% MoM Mar 2026; DB 130 index. Frontend MoM.",
        "verified": True,
    },
    "retirement-age-men": {
        "source": "curated",
        "te_label": "National Revenue Agency",
        "te_page": "https://tradingeconomics.com/bulgaria/retirement-age-men",
        "te_url": "https://www.nra.bg",
        "verified": True,
    },
    "retirement-age-women": {
        "source": "curated",
        "te_label": "National Revenue Agency",
        "te_page": "https://tradingeconomics.com/bulgaria/retirement-age-women",
        "te_url": "https://www.nra.bg",
        "verified": True,
    },
    "sales-tax-rate": {
        "source": "curated",
        "te_label": "National Revenue Agency, Bulgaria",
        "te_page": "https://tradingeconomics.com/bulgaria/sales-tax-rate",
        "te_url": "https://www.nra.bg",
        "note": "BG VAT 20%.",
        "verified": True,
    },
    "services-inflation": {
        "source": "eurostat",
        "te_page": "https://tradingeconomics.com/bulgaria/services-inflation",
        "note": "TE has NO BG page. EconPulse-internal via Eurostat ei_cphi_m CP-HIS.",
        "verified": True,
    },
    "services-sentiment": {
        "source": "eurostat",
        "te_page": "https://tradingeconomics.com/bulgaria/services-sentiment",
        "note": "TE has NO BG page. EconPulse-internal via Eurostat ei_bsse_m_r2 SCI.",
        "verified": True,
    },
    "social-security-rate": {
        "source": "curated",
        "te_label": "National Revenue Agency, Bulgaria",
        "te_page": "https://tradingeconomics.com/bulgaria/social-security-rate",
        "te_url": "https://www.nra.bg",
        "verified": True,
    },
    "social-security-rate-companies": {
        "source": "curated",
        "te_label": "National Revenue Agency, Bulgaria",
        "te_page": "https://tradingeconomics.com/bulgaria/social-security-rate-for-companies",
        "te_url": "https://www.nra.bg",
        "verified": True,
    },
    "social-security-rate-employees": {
        "source": "curated",
        "te_label": "National Revenue Agency, Bulgaria",
        "te_page": "https://tradingeconomics.com/bulgaria/social-security-rate-for-employees",
        "te_url": "https://www.nra.bg",
        "verified": True,
    },
    "terrorism-index": {
        "source": "curated",
        "te_label": "Institute for Economics and Peace",
        "te_page": "https://tradingeconomics.com/bulgaria/terrorism-index",
        "te_url": "https://www.economicsandpeace.org",
        "verified": True,
    },
    "unemployed-persons": {
        "source": "eurostat",
        "te_label": "Ministry of Labour and Social Policy, Bulgaria",
        "te_page": "https://tradingeconomics.com/bulgaria/unemployed-persons",
        "te_url": "https://www.mlsp.government.bg",
        "note": "Eurostat une_rt_m THS_PER. TE 151.12k Mar 2026 (MLSP registered); DB 97k (Eurostat ILO). Concept diff documented.",
        "verified": True,
    },
    "unemployment": {
        "source": "eurostat",
        "te_label": "Ministry of Labour and Social Policy of the Republic of Bulgaria",
        "te_page": "https://tradingeconomics.com/bulgaria/unemployment-rate",
        "te_url": "https://www.mlsp.government.bg",
        "note": "Eurostat ei_lmhr_m LM-UN-T-TOT. TE 5.3% Mar 2026 (MLSP); DB 3.2% (Eurostat ILO). Concept diff.",
        "verified": True,
    },
    "youth-unemployment-rate": {
        "source": "eurostat",
        "te_label": "EUROSTAT",
        "te_page": "https://tradingeconomics.com/bulgaria/youth-unemployment-rate",
        "te_url": "https://ec.europa.eu/eurostat/",
        "verified": True,
    },
}


def main():
    # Load existing
    with open("docs/te_sources_truth.yaml", encoding="utf-8") as f:
        truth = yaml.safe_load(f)
    bg = truth.setdefault("BG", {})
    for slug, entry in UPDATES.items():
        cur = bg.get(slug, {})
        new = dict(cur)
        new.update(entry)
        new["reaudited"] = TODAY
        bg[slug] = new
    with open("docs/te_sources_truth.yaml", "w", encoding="utf-8") as f:
        yaml.safe_dump(truth, f, sort_keys=True, allow_unicode=True, width=140)
    print(f"Updated BG truth.yaml: {len(UPDATES)} entries")


if __name__ == "__main__":
    main()
